#!/bin/bash

PROFILE=dev
VER=$(cat version.txt | sed 's/ //g')

DB_URL=jdbc:mariadb://mariadb-ver10-01.c3edzk8fothj.ap-northeast-2.rds.amazonaws.com:3306/ZIPSA_DEV?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useUnicode=true
DB_USERNAME=admin
DB_PASSWORD=Na6080su12!!

RABBITMQ_HOST=144.24.83.179
RABBITMQ_PORT=5672
RABBITMQ_VIRTUAL_HOST=/
RABBITMQ_USERNAME=sky114z
RABBITMQ_PASSWORD=na6080su12!@

REDIS_HOST=144.24.83.179
REDIS_PORT=6379
REDIS_PASSWORD=na6080su12!@

AWS_ACCESS_KEY=AKIA442EBW2WH4TXKELQ
AWS_SECRET_KEY=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
AWS_REGION=ap-northeast-2
DYNAMO_ENDPOINT=https://dynamodb.ap-northeast-2.amazonaws.com
S3_BUCKET=seonjaena
S3_DIR_PREFIX=dev/jwt-test

gradle wrapper
./gradlew clean build -x test -Pprofile=$PROFILE
java -DDB_URL=$DB_URL -DDB_USERNAME=$DB_USERNAME -DDB_PASSWORD=$DB_PASSWORD \
      -DRABBITMQ_HOST=$RABBITMQ_HOST -DRABBITMQ_PORT=$RABBITMQ_PORT -DRABBITMQ_VIRTUAL_HOST=$RABBITMQ_VIRTUAL_HOST -DRABBITMQ_USERNAME=$RABBITMQ_USERNAME -DRABBITMQ_PASSWORD=$RABBITMQ_PASSWORD \
      -DREDIS_HOST=$REDIS_HOST -DREDIS_PORT=$REDIS_PORT -DREDIS_PASSWORD=$REDIS_PASSWORD \
      -DAWS_ACCESS_KEY=$AWS_ACCESS_KEY -DAWS_SECRET_KEY=$AWS_SECRET_KEY -DAWS_REGION=$AWS_REGION -DDYNAMO_ENDPOINT=$DYNAMO_ENDPOINT -DS3_BUCKET=$S3_BUCKET -DS3_DIR_PREFIX=$S3_DIR_PREFIX \
      -Dspring.profiles.active=$PROFILE \
      -jar build/libs/zipsa-$VER.jar