
spring:

  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

  devtools:
    restart:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
  config: classpath:logback-spring.xml

local:
  win:
    dir-prefix: C:/Users/sky11/zipsa-files
  linux:
    dir-prefix: /root/zipsa-files
  mac:
    dir-prefix: /Users/naseonjae/zipsa-files


token:
  # 5분 (1000 * 60 * 5 = 300000) / 30분 (1000 * 60 * 30 = 1800000) / 1시간 (1000 * 60 * 60 = 3600000)
  access-expire: 1800000
  # 1일 (1000 * 60 * 24 = 1440000) / 1달 (1000 * 60 * 24 * 31 = 44640000)
  refresh-expire: 1440000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://mariadb-ver10-01.c3edzk8fothj.ap-northeast-2.rds.amazonaws.com:3306/ZIPSA_DEV?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useUnicode=true
    username: admin
    password: Na6080su12!!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    open-in-view: false

cloud:
  aws:
    credentials:
      access-key: AKIA442EBW2WH4TXKELQ
      secret-key: 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
    dynamodb:
      endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
    region:
      static: ap-northeast-2
    s3:
      bucket: seonjaena
      dir-prefix: dev/jwt-test
    stack:
      auto: false


---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://mariadb-ver10-01.c3edzk8fothj.ap-northeast-2.rds.amazonaws.com:3306/ZIPSA_DEV?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useUnicode=true
    username: admin
    password: Na6080su12!!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
    open-in-view: false

cloud:
  aws:
    dynamodb:
      endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
    region:
      static: ap-northeast-2
    s3:
      bucket: seonjaena
      dir-prefix: prod/jwt-test
    stack:
      auto: false